flaskblog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_ckeditor import CKEditor
from flask_migrate import Migrate
from flask_simple_geoip import SimpleGeoIP
from flaskblog.config import Config


db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()


login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'



mail = Mail()
ckeditor = CKEditor()
simple_geoip = SimpleGeoIP()

from flaskblog.commands.command import command
from flaskblog.users.routes import users
from flaskblog.categories.routes import categories
from flaskblog.tags.routes import tags
from flaskblog.posts.routes import posts
from flaskblog.main.routes import main




def create_app(config_class=Config):
    app = Flask(__name__)
    app.config["GEOIPIFY_API_KEY"] = "at_0h5dzAeV8tUbNswceLLQos3dazKA5"
    db.init_app(app) 
    migrate.init_app(app, db) 
    bcrypt.init_app(app)  
    mail.init_app(app)
    login_manager.init_app(app)
    ckeditor.init_app(app)
    simple_geoip.init_app(app)

    app.config.from_object(Config)
    app.register_blueprint(command)
    app.register_blueprint(users)
    app.register_blueprint(categories)
    app.register_blueprint(tags)
    app.register_blueprint(posts)
    app.register_blueprint(main)

    return app

flaskblog/categories/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db

from flaskblog.models import Post, Category
from flaskblog.categories.forms import CategoryForm
from flaskblog.decorators import is_admin

categories = Blueprint('categories', '__name__')


# Create Category
@categories.route('/create-category', methods=['GET', 'POST'])
@login_required
@is_admin
def create_category():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        flash(f'"{category.name}" category has been created!', 'success')
        return redirect(url_for('categories.create_category'))
    return render_template('categories/category-form.html', title='Create Category', form=form)


# Update Category
@categories.route('/update-category/<int:id>', methods=['GET', 'POST'])
@login_required
@is_admin
def update_category(id):
    category = Category.query.get_or_404(id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category has been Updated!', 'success')
        return redirect(url_for('main.home'))
    else:
        form.name.data = category.name
    return render_template('categories/category-form.html', title='Update Category', form=form)

# Category details
@categories.route('/category-detail/<int:id>', methods=['GET'])
def category_detail(id):
    category = Category.query.get(id)
    return render_template('categories/category-detail.html', title='Categories', category=category)

flaskblog/main/routes.py
from flask import render_template, request, Blueprint, redirect
from flask_login import current_user, login_required
from flask_login import login_required

from flaskblog.models import Post, Category, Activity
from flaskblog.decorators import is_admin

import requests
import json

from flask import Flask, jsonify
from flaskblog import simple_geoip, db
from flaskblog.decorators import create_user_acts
main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
@create_user_acts
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(is_public=True).order_by(
        Post.created_at.desc()).paginate(page, per_page=10)
    categories = Category.query.all()

    return render_template('home.html', home='Home', posts=posts, categories=categories)


@main.route('/about')
@create_user_acts
def about():
    return render_template('about.html', title='About')


@main.route('/search', methods=['GET'])
def search():
    page = request.args.get('page', 1, type=int)
    # Search
    search_value = request.args.get('search')

    posts = Post.query.filter(
        Post.title.contains(search_value) |
        Post.summary.contains(search_value) |
        Post.content.contains(search_value) |
        Post.tags.any(name=search_value) |
        Post.tags.any(slug=search_value)
    ).paginate(page, per_page=50)

    categories = Category.query.all()
    return render_template('home.html', title='search', posts=posts, categories=categories)


@main.route('/view-activities')
@login_required
@is_admin
def view_activities():
    # order_by(Activity.created_at.desc()
    acts = Activity.query.order_by(Activity.created_at.desc()).all()
    return render_template('activity.html', title='Activity', acts=acts)


@main.route('/get-activities', methods=['GET', 'POST'])
@login_required
@is_admin
def get_activities():
    query = Activity.query
    search = request.form.get('search[value]')
    if search:
        query = query.filter(
            Activity.ip_address.contains(search) |
            Activity.path.contains(search) |
            Activity.created_at.contains(search)
        )

    recordsFiltered = query.count()

    # pagination
    page = request.form.get('start')
    length = request.form.get('length')
    query = query.order_by(Activity.created_at.desc()
                           ).offset(page).limit(length)

    data = [item.to_dict() for item in query]
    output = {
        'draw': request.form.get('draw'),
        'recordsTotal': Activity.query.count(),
        'recordsFiltered': recordsFiltered,
        'data': data,
        'request_data': request.form.get('start')
    }
    return jsonify(output)

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Category, Tag, Like, Comment
from flaskblog.posts.forms import PostForm, CommentForm, ReplyForm
from slugify import slugify

posts = Blueprint('posts', __name__)


# Create Post
@posts.route('/create-post', methods=['GET', 'POST'])
@login_required
def create_post():
    tags = Tag.query.all()
    form = PostForm()
    form.category.choices = [(g.id, g.name)
                             for g in Category.query.order_by('name')]
    if form.validate_on_submit():
        post = Post(title=form.title.data, summary=form.summary.data,
                    content=form.content.data, is_public=form.public.data,
                    category_id=form.category.data, author=current_user)

        tags = request.form.getlist('tags')
        for item in tags:
            tag = Tag.query.get(item)
            print(item)
            post.tags.append(tag)

        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))

    return render_template('posts/post-form.html', title='Create Post', form=form, tags=tags)


@posts.route('/post-detail/<int:id>', methods=['GET', 'POST'], strict_slashes=False)
def post_detail(id):
    post = Post.query.filter_by(id=id).first_or_404()
    commentForm = CommentForm()
    replyForm = ReplyForm()
    comments = Comment.query.filter_by(
        post_id=post.id).order_by(Comment.path.asc())

    if commentForm.validate_on_submit():
        text = commentForm.comment.data

        comment = Comment(
            text=text,
            user_id=current_user.id,
            post_id=post.id,
        )

        comment.save()
        flash("Your comment has been created! ", "success")
        return redirect(url_for('posts.post_detail', id=id))
    return render_template('posts/post-detail.html',
                           title='Post Detail',
                           post=post,
                           commentForm=commentForm,
                           replyForm=replyForm,
                           comments=comments,)


@posts.route("/<int:post_id>/<int:comment_id>", methods=("GET", "POST"), strict_slashes=False)
@login_required
def reply_comment(post_id, comment_id):
    replyForm = ReplyForm()
    post = Post.query.get_or_404(post_id)
    parent = Comment.query.get_or_404(comment_id)

    if replyForm.validate_on_submit():
        text = replyForm.reply.data

        comment = Comment(
            parent=parent,
            text=text,
            swap_id='',
            user_id=current_user.id,
            post_id=post.id,
        )
        comment.save()
    replyForm.reply.data = None
    return render_template('posts/partial/reply.html', replyForm=replyForm, comment=comment, post=post)


@posts.route('/like_or_dislike/<int:id>', methods=['POST'])
@login_required
def like_or_dislike(id):
    post = Post.query.get_or_404(id)
    # like = any(like.user.id == current_user.id for like in post.likes)
    like_id = None
    for like in post.likes:
        if like.user.id == current_user.id:
            like_id = like.id
            break
    if like_id:
        db.session.delete(Like.query.get(like_id))
        total_likes = post.total_likes or 0
        post.total_likes = total_likes - 1
    else:
        like = Like(post_id=id, user_id=current_user.id)
        db.session.add(like)
        total_likes = post.total_likes or 0
        post.total_likes = total_likes + 1
    db.session.commit()

    return render_template('posts/partial/like.html', post=post)


@posts.route('/post-update/<int:id>', methods=['GET', 'Post'])
@login_required
def post_update(id):
    post = Post.query.get_or_404(id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    form.category.choices = [(c.id, c.name)
                             for c in Category.query.order_by('name')]

    if form.validate_on_submit():
        post.title = form.title.data
        post.summary = form.summary.data
        post.content = form.content.data
        post.is_public = form.public.data
        post.category_id = form.category.data
        post.user = current_user

        tags = request.form.getlist('tags')
        updated_tags = list()
        if tags:
            for item in tags:
                tag = Tag.query.get(item)
                if tag:
                    updated_tags.append(tag)
        post.tags = updated_tags

        db.session.commit()

        flash('Your post has been Updated!', 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.category.data = post.category_id
        form.title.data = post.title
        form.summary.data = post.summary
        form.content.data = post.content
        form.public.data = post.is_public
        tags = Tag.query.all()

    return render_template('posts/post-form.html', title='Post Update', form=form, tags=tags, post=post)



# htmx request
@posts.route('/post-delete/<int:id>', methods=['POST'])
@login_required
def post_delete(id):
    post = Post.query.get_or_404(id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    return ''

flaskblog/tags/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Tag, Post
from flaskblog.tags.forms import TagForm
from slugify import slugify

tags = Blueprint('tags', '__name__')

# Create tag
@tags.route('/create-tag', methods=['GET', 'POST'])
@login_required
def create_tag():
    form = TagForm()
    if form.validate_on_submit():
        slug = slugify(form.name.data)
        tag = Tag(name=(form.name.data).lower(), slug=slug)
        db.session.add(tag)
        db.session.commit()
        flash(f'"{tag.name}" has been created!', 'success')
        return redirect(url_for('tags.create_tag'))
    return render_template('tags/tag-form.html', title='Create Tag', form=form)


@tags.route('/update-tag/<int:id>', methods=['GET', 'POST'])
@login_required
def update_tag(id):
    tag = Tag.query.get_or_404(id)
    form = TagForm()
    if form.validate_on_submit():
        tag.slug = slugify(form.name.data)
        tag.name = (form.name.data).lower()
        db.session.commit()
        flash('Tag has been Updated!', 'success')
        return redirect(url_for('main.home'))
    else:
        form.name.data = tag.name
    return render_template('tags/tag-form.html', title='Update tag', form=form)


@tags.route('/post-by-tag/<slug>', methods=['GET'])
def post_by_tag(slug):
    tag = Tag.query.filter_by(slug=slug).first()
    posts = Post.query.filter(Post.tags.any(slug=slug))
    return render_template('tags/post-by-tag.html', title='Posts by tag', tag=tag, posts=posts)

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (UserRegistrationForm, LoginForm, UserUpdateForm,
                                   PasswordResetRequestForm, PasswordResetForm)
from flaskblog.users.utils import save_picture, send_password_reset_mail
users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = UserRegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    context = {
        'title': 'User Registration',
        'form': form,
    }
    return render_template('accounts/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.rememberme.data)
            flash('Login Successful!', 'success')
            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful! Please provide valid credentials.', 'danger')

    return render_template('accounts/login.html', title='Login', form=form)


@users.route('/update_profile', methods=['GET', 'POST'])
def update_profile():
    form = UserUpdateForm()
    if form.validate_on_submit():
        if form.image.data:
            picture_file = save_picture(form.image.data)
            print(picture_file)
            current_user.image = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your profile has been updated!', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('accounts/update-profile.html', title='Update Profile', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route("/profile")
@login_required
def profile():
    image = url_for('static', filename='profile_pic/' + current_user.image)
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(author=current_user)\
        .order_by(Post.created_at.desc())\
        .paginate(page, per_page=10)
    # return render_template('user-posts.html', home='Home', posts=posts, user=user)

    return render_template('accounts/profile.html', title=current_user.username, posts=posts, image=image)


@users.route('/password/reset/request', methods=['GET', 'POST'])
def password_reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_password_reset_mail(user)
        flash('An email has been sent with instruction to reset your password!', 'success')
        return redirect(url_for('users.login'))
    return render_template('accounts/password-reset-request.html', title='Password Reset Request', form=form)


@users.route('/reset/password/<token>', methods=['GET', 'POST'])
def reset_password_token(token):
    if current_user.is_authenticated:
        return redirect('home')
    user = User.verify_reset_token(token)
    if user is None:
        flash('This is an invalid or expired token', 'danger')
        return redirect(url_for('users.password_reset_request'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash('Your account has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('accounts/reset-password-token.html', title='Reset Password', form=form)

flaskblog/templates/accounts/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />
    <title>Sign Up | Code Blog</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet"
        type="text/css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css" />

    <!-- Bootstrap core CSS -->
    <link href=" {{ url_for('static', filename='css/bootstrap.min.css') }} " rel="stylesheet" />

    <!-- BSB -Start -->
    <!-- Waves Effect Css -->
    <link href="{{ url_for('static', filename='plugins/node-waves/waves.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ url_for('static', filename='plugins/animate-css/animate.css') }}" rel="stylesheet" />

    <!-- Bsb Css -->
    <link href="../static/vendor/bsb/css/style.css" rel="stylesheet" />
    <!-- BSB - End -->
</head>

<body>
    <main class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class=" mt-2 alert alert-{{ category }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
        <div>
            {% block content %}

            {% endblock %}
        </div>
    <!-- Jquery Core Js -->
    <script src="{{ url_for('static', filename='plugins/jquery/jquery.min.js') }}"></script>

    <!-- BSB Js - Start -->
    <!-- Waves Effect Plugin Js -->
    <script src="{{ url_for('static', filename='plugins/node-waves/waves.js') }}" rel="stylesheet"></script>

    <!-- Validation Plugin Js -->
    <script src=" {{ url_for('static', filename='plugins/jquery-validation/jquery.validate.js') }} "></script>

    <!-- Custom Js -->
    <script src=" {{ url_for('static', filename='js/admin.js') }} "></script>
    <script src="{{ url_for('static', filename='js/pages/sign-up.js') }}" rel="stylesheet"></script>
    <script src="{{ url_for('static', filename='js/pages/sign-in.js') }}" rel="stylesheet"></script>
    <!-- BSB Js - End -->
</body>

</html>

flaskblog/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block page_wise_css %} 

{% endblock page_wise_css %}
{% block content %}
<div class="login-page">
    <div class="login-box">
        <div class="logo">
            <a href="{{ url_for('main.home') }}" class="text-danger waves-effect" style="color: #E91E63;"><b>CODE BLOG</b></a>
            <small class="text-info">A coding platform</small>
        </div>
        <div class="card">
            <div class="body">
                <form id="sign_in" method="POST" action="">
                    {{ form.hidden_tag() }}
                    <div class="msg">Sign in to start your session</div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            {% if form.email.errors %}
                                {{ form.email(class="form-control", placeholder="Email", autofocus="on") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                                {{ form.email(class="form-control", placeholder="Email", autofocus="on") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            {% if form.email.errors %}
                                {{ form.password(class="form-control", placeholder="Password", autofocus="on") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                                {{ form.password(class="form-control", placeholder="Password", autofocus="on") }}
                            {% endif %}
                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-8 p-t-5">
                            {{ form.rememberme(class="filled-in chk-col-pink") }}
                            {{ form.rememberme.label() }}
                        </div>
                        <div class="col-xs-4">
                            <button class="btn btn-block bg-pink waves-effect" type="submit">SIGN IN</button>
                        </div>
                    </div>
                    <div class="row m-t-15 m-b-20">
                        <div class="col-6">
                            <a href="{{ url_for('users.register') }}">Register Now!</a>
                        </div>
                        <div class="col-6 align-right">
                            <a href="{{ url_for('users.password_reset_request') }}">Forgot Password?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

flaskblog/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="row g-5">
    <div class="col-sm-12 col-md-5 col-lg-4">
        <div class="card position-sticky" style="top: 2rem;">
          <div class="card-body">
            <div class="d-flex flex-column justify-content-center align-items-center">
                <img src="{{ url_for('static', filename='profile_pic/' + current_user.image) }}" class="rounded mx-auto d-block rounded-circle border" width="150" height="150" alt="...">
                <div class="text-center mt-3">
                    <h5 class="card-title">{{ current_user.username }}</h5>
                    <p>{{ current_user.email }}</p>
                    <a href="{{ url_for('users.update_profile') }}" class="text-primary text-decoration-none">Edit</a>
                </div>
            </div>
          </div>
        </div>
      </div>
    <div class="col-sm-12 col-md-7 col-lg-8">
      <div class="row mb-2">
        {% for post in posts.items %}
        <div class="col-md-12" hx-target="this" hx-swap="outerHTML">
          <div
            class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative bg-white">
            <div class="col p-4 d-flex flex-column position-static">
              <div class="border-bottom mb-3 p-1 d-flex justify-content-between align-items-center">
                <div>
                  <img src="{{ url_for('static', filename='profile_pic/' + post.author.image) }}" alt="mdo" width="32"
                    height="32" class="rounded-circle">

                  <strong class="d-inline-block mb-2 text-primary"> {{ post.author.username|capitalize }} </strong>
                  <span class="mb-1 text-muted"> | {{ post.created_at.strftime('%d %b, %y') }} </span>
                  <span class="mb-1 text-muted"> | <i class="fas fa-globe-asia"></i> </span>
                </div>
                {% if post.author == current_user %}
                <div class="p-1">
                  <div class="dropdown">
                    <a href="javascript:void(0)" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <li><a href="{{ url_for('posts.post_update', id=post.id) }}" class="text-primary dropdown-item"><i class="fas fa-edit"></i> Edit</a></li>
                      <li><a hx-post="{{ url_for('posts.post_delete', id=post.id) }}" hx-confirm="Are you sure you wish to delete?" href="javascript:void(0)" class="text-danger dropdown-item"><i class="fas fa-trash"></i> Delete</a></li>
                    </ul>
                  </div>
                </div>
                {% endif %}
              </div>
              <!-- Post Tags  -->
              <div class="text-end">
                {% for tag in post.tags %}
                <a href="{{ url_for('tags.post_by_tag', slug=tag.slug) }}"><span class="badge bg-secondary">{{ tag.slug }}</span></a>
                {% endfor %}
              </div>
              <!-- ./Post Tags  -->
              <article class="blog-post">
                <h5 class="mb-1"> {{ post.title }} </h5>
                <p>
                  {{ post.summary }}
                  <a href=" {{ url_for('posts.post_detail', id=post.id) }} ">Continue reading</a>
                </p>
              </article>
            </div>
            <!-- Like and Comment Section -->
            <div class="d-flex justify-content-around p-3 bg-light">
              <!-- Like  -->
              <div hx-target="this" hx-swap="outerHTML" 
                data-toggle="tooltip" 
                data-placement="top" 
                title="Please login first to like.">
                <a class="text-decoration-none 
                  {% if not current_user.is_authenticated %}btn disabled{% endif %}"
                    hx-post="{{ url_for('posts.like_or_dislike', id=post.id) }}" 
                    href="javascript:void(0)">
                  {% if post.user_has_like %}
                    <i class="fas fa-heart fa-md text-danger"></i>
                  {% else %}
                    <i class="fas fa-heart fa-md text-secondary"></i>
                  {% endif %}
                </a>
                <span class="ml-2">{{ post.total_likes or 0 }}</span>
              </div>
              <!-- Comment  -->
             <div data-toggle="tooltip" data-placement="top" title="Please login first to comment.">
              <a class="{% if not current_user.is_authenticated %}btn disabled{% endif %}" 
                href="{{ url_for('posts.post_detail', id=post.id) }}#comment-section">
                <i class="fas fa-comment-alt fa-md text-secondary"></i></a>
              <span class="ml-2">{{ post.comments.__len__() }}</span>
             </div>
            </div>
            <!-- ./Like and Comment Section -->
          </div>
        </div>
        {% endfor %}
      </div>
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if posts.has_prev %}
              <li class="page-item">
                <a class="page-link" href="{{ url_for('users.profile', page=posts.prev_num) }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.profile', page=posts.prev_num) }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {% endif %}
    
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if page_num %}
                {% if posts.page == page_num %}
                  <li class="page-item active" aria-current="page"><a class="page-link active" href="{{ url_for('users.profile', page=page_num) }}">{{ page_num }}</a></li>
                {% else %}
                  <li class="page-item"><a class="page-link" href="{{ url_for('users.profile', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}          
              {% endif %}
            {% endfor %}
            {% if posts and posts.has_next %}
              <li class="page-item">
                <a class="page-link" href="{{ url_for('users.profile', page=posts.next_num) }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>
</div>
{% endblock content %}